### ISSUE TITLE
Has this been tested on OS X?

### ISSUE THREAD

**Issue by axos88** [jcreekmore/timeout-readwrite-rs#4]
Hello,

It seems this is constantly returning with a read size of 0 instead of blocking in os x. Has this been tested? 

```
            let f = File::open("foo.txt", ).unwrap();
            let mut rdr = TimeoutReader::new(f, Duration::new(1, 0));

            loop {
                let mut s = Vec::<u8>::new();

                loop {
                    let mut buf = [0u8; 10];
                    let r = rdr.read(&mut buf);
                    match r {
                        Ok(0) => break,
                        Ok(cnt) => {
                            debug!(cnt);
                            if (buf[0] != 96) {
                                s.extend_from_slice(&buf[..cnt]);
                            }
                        },
                        Err(e) => debug!(e)
                    }
                }

                debug!("Block recevied!")


                if (s.len() > 0) {
                    debug!(s);
                    let str: String = String::from_utf8(s.clone()).unwrap();
                    http_authenticator.send(HttpAuthenticatorMessage::Authorize(str));
                }

            }
```

**Comment by axos88** [comment]
Hmm I guess related to #3?

**Comment by axos88** [comment]
From:  https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/

The new error looks similar to the old problem: when there’s nothing to wait for and we ask poll() to wait N milliseconds, the 10.12 version of poll() returns immediately without waiting. Causing busy-loops. The problem has been reported to Apple and its Radar number is 28372390. (There has been no news from them on how they plan to act on this.)

**Comment by jcreekmore** [comment]
@axos88 so, my development machine is macOS 10.13(.3) High Sierra and I don't have any issues. My test cases run through reading a file with a timeout and that works just fine on my High Sierra machine. I also have an example that lets me run an arbitrary program. I ran something like:
```
mkfifo tst
cargo run --example process -- cat tst
```
and it another window ran:
```
echo "foo" >> tst
```
and everything seemed to work fine.

The article you linked seems to imply that the poll bug was fixed in macOS 10.12.2. What version of macOS are you seeing the problem on?

The only way I really see to work around this would be to have an option for using `select` vs `poll` (and hope that `select` has better behavior) which would not be terrible short of increasing the code size by providing different versions of the `wait_until_ready` function depending on platform. 

Would you be interested in providing a PR to do that?

**Comment by axos88** [comment]
10.12.6, but it still seems that something is broken, i will clean up my code and post it in a bit

**Comment by axos88** [comment]
Does this work for you?

```
#include <poll.h>
#include <stdio.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

int main(void)
{
  struct timeval before, after;
  int rc;
  size_t us;
  struct pollfd pfd;

  int fd = open("foo.blah", O_RDONLY);
  printf("fd=%d\n", fd);

  pfd.fd = fd;
  pfd.events = POLLIN;

  gettimeofday(&before, NULL);
  rc = poll(&pfd, 1, 5000); // 5 sec
  gettimeofday(&after, NULL);

  us = (after.tv_sec - before.tv_sec) * 1000000 +
    (after.tv_usec - before.tv_usec);

  if(us < 400000) {
    puts("poll() is broken\n");
  }
  else {
    printf("poll() works: %d\n", us);
  }

  char *buf = malloc(50);
  memset(buf, 0, 50);

  int size = read(fd, buf, 50);

  printf("size=%d buf=%s\n", size, buf);


  return 0;
}
```

**Comment by axos88** [comment]
For me it return immediatly, without waiting at the poll or the read, reading as much data as is in the file already, or 0 bytes if it is empty.

**Comment by axos88** [comment]
with fopen / fread it seems to always wait at the poll, no matter the contents of the file.

**Comment by axos88** [comment]
Scratch that, it doesn't work with fopen either - just haven't used the fd returned by fileno() beforehand. Same behaviour.

**Comment by jcreekmore** [comment]
Ah, so with that program (and a little bit of backing into it), I see the behavior you are seeing. However, I am not sure that that is wrong.
> poll() returns the number of descriptors that are ready for I/O, or -1 if an error
     occurred.  If the time limit expires, poll() returns 0.  If poll() returns with an
     error, including one due to an interrupted call, the fds array will be unmodified
     and the global variable errno will be set to indicate the error.

I mean, you opened the file and it _is_ ready for I/O. For a file, poll doesn't make that much sense, because the file is always ready for I/O. So, it is correct for it to return immediately with the file descriptor and, if the file is empty, to return you a 0-byte read.

**Comment by axos88** [comment]
oh crap... everything is a file under linux... except they're actually not.
Let me check this

**Comment by axos88** [comment]
🤦‍♂️

**Comment by jcreekmore** [comment]
So, if it helps, my original use case for this was waiting on a process to complete sending data out stdout, but not waiting too long.

**Comment by axos88** [comment]
Can you post a message on the readme.md that this is NOT supposed to work with real files... :|

**Comment by jcreekmore** [comment]
I can. I mean, it does, it just isn't doing what you are expecting. I think what you are going to want is some loop around a read call that, if enough data isn't available, sleeps and then wakes up to try to read more data if you are feeding data in externally through a file.

**Comment by axos88** [comment]
I mean yeah... that's the workaround i have set up right now, but... how does tail work?

**Comment by axos88** [comment]
Hmm... exactly the same way: http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/tail.c #1286.
